repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.8
  hooks:
    - id: ruff-format # formatter
      types_or: [python, pyi, jupyter, toml]

    - id: ruff # linter
      types_or: [python, pyi, jupyter, toml]
      args: ["check", "--select", "I", "--fix"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0  
  hooks:
    - id: mypy
      language: system
