configuration:
  executable: "example"
  experiment_name: "experiment"
  golden_result_condition: "win"
  result_condition: [
    "foo",
    "main",
  ]
  number_of_runs: 10

  gdb:
    gdb_path: "gdb"
    # embedded: false
    # board_family: "stm32"
    # remote: "localhost:1234"

  timeout_interval: #in ms
    min: 59000
    max: 60000
  injection_delay: #in ms
    min: 5000
    max: 10000


injector: "example_csv.csv"
