configuration:
  executable: "foo"
  experiment_name: "experiment"
  golden_result_condition: "win"
  result_condition: [
    "foo",
    "main"]
  number_of_runs: 1

  gdb:
    gdb_path: "gdb"
    remote: "localhost:1234" #true or false
    embedded: false

  timeout_interval: #in seconds
    min: 59
    max: 60
  injection_delay: #in seconds
    min: 5
    max: 10


injector: "example_csv.csv"
